korp_backend_url: https://backend.korp.altlab.dev/
languages:
  - value: eng
    label: English
word_picture: false
has_timespan: false
folders:
  - plainscree:
    title: nêhiyawêwin (Plains Cree) texts
    description: nêhiyawêwin (Plains Cree) texts
    contents:
      - wolfart_ahenakew
      - bloomfield