label: Default Mode
preselected_corpora:
  - wolfart_ahenakew
  - bloomfield
default_within:
  sentence: sentence
folders:
  plainscree:
    title: nêhiyawêwin (Plains Cree) texts
    description: nêhiyawêwin (Plains Cree) texts