version: "3"

services:
  korp-backend:
    restart: always
    hostname: korp-backend-container
    build: ./backend/
    ports:
      - "1235:1234" # gunicorn server
    volumes:

    # LFS mounts
    - "/data_local/application-data/korp-backend/corpora:/corpora"
    - "/data_local/application-data/korp-backend/vrt_files:/vrt_files"
    - "/data_local/application-data/korp-backend/auth:/auth"

  korp-frontend:
    restart: always
    hostname: korp-frontend-container
    build: ./frontend/
    ports:
      - "9112:80" # frontend loader
