version: "3"

services:
  korp-backend:
    restart: always
    hostname: korp-backend-container
    build: ./backend/
    ports:
      - "1234:1234" # gunicorn server
    volumes:

    # LFS mounts
    - "/Users/data_local/application-data/korp-backend/corpora:/corpora"
    - "/Users/data_local/application-data/korp-backend/vrt_files:/vrt_files"